import almonds from "./almond.jpg"
import anjeer from "./anjeer.jpg"
import apple from "./apple.webp"
import banana from "./banana.webp"
import bananachips from "./bananachips.jpg"
import bread from "./bread.webp"
import bringal from "./bringal.webp"
import brownchana from "./brownchana.webp"
import butter from "./butter.jpg"
import capsicum from "./capsicum.avif"
import cardamom from "./cardamom.webp"
import chana from "./chana.jpg"
import chanadal from "./chanadal.jpg"
import chashew from "./chashew.jpg"
import cheese from "./cheese.jpg"
import cheeseballs from "./cheeseballs.webp"
import chickenmasala from "./chickenmasala.webp"
import chilie from "./chilie.avif"
import chocolate from "./chocolate.jpg"
import cookie from "./cokkie.jpg"
import curd from "./curd.webp"
import dates from "./dates.jpg"
import grapes from "./grapes.webp"
import greenpeas from "./greenpeas.webp"
import gulabjamun from "./gulabjamun.webp"
import kitkat from "./kitkat.webp"
import kurkure from "./kurkure.webp"
import lays from "./lays.jpg"
import makhana from "./makhana.jpg"
import mango from "./mango.webp"
import sidmango from "./mango2.webp"
import masoor from "./masoor.jpg"
import masoordal from "./masoordal.webp"
import matki from "./matki.webp"
import milk from "./milk.avif"
import mixdal from "./mixdal.jpg"
import mixedsprouts from "./mixedsproutes.webp"
import momos from "./momos.webp"
import moong from "./moong.jpg"
import moongdal from "./moongdal.jpg"
import moongsprout from "./moongsprout.webp"
import Nachos from "./Nachos.webp"
import nuggets from "./nuggets.jpg"
import oats from "./oats.jpg"
import onion from "./onion.jpg"
import orange from "./orange.jpg"
import paneermasala from "./paneermasala.jpg"
import pavbhajimasala from "./pavbhajimasala.jpeg"
import peanuts from "./peanuts.jpg"
import pista from "./pista.jpg"
import potato from "./potato.jpg"
import pav from "./pav.webp"
import pomegranate from "./pomegranate.webp"
import puff from "./puff.webp"
import rasins from "./rasins.webp"
import redchilipowder from "./redchilipowder.webp"
import tomatoes from "./tomatoes.webp"
import turmeric from "./turmeric.webp"
import urad from "./urad.webp"
import watermellon from "./watermellon.webp"
import rajma from "./rajma.jpg"
import redcapsicum from "./redcapsicum.avif"
import strawberry from "./strawberry.jpg"
import sweetlime from "./sweetlime.jpg"
import walnut from "./walnut.jpg"
import fish from "./fish.jfif"
import chickenKheema from "./chickenKheema.jfif"
import chicken from "./chicken.jfif"
import eggs from "./eggs.webp"
import chickendrum from "./chickendrum.webp"
import notfound from "./notfound.svg"

export {almonds, anjeer, apple, banana, bananachips,bread,bringal,brownchana,butter,capsicum
        , cardamom,chana,chanadal,chashew,cheese,cheeseballs,chicken,chickenKheema,chickendrum
    ,chickenmasala,chilie,chocolate,cookie,curd,dates,eggs,fish,grapes,greenpeas
    ,gulabjamun, kitkat,kurkure,lays,makhana,mango,sidmango,masoor,masoordal
    ,matki,milk,mixdal,mixedsprouts,momos,moong,moongdal,moongsprout,Nachos,nuggets
    ,oats,onion,orange,paneermasala,pav,pavbhajimasala,peanuts
    ,pista,pomegranate,potato,puff,rajma,rasins,redcapsicum,redchilipowder
    ,strawberry,sweetlime,tomatoes,turmeric,urad,walnut,watermellon,notfound} 